crossborder_sql:
  outputs:
    dev:
      account: qc28226.eu-west-1
      database: "{{env_var('DBT_SNOWFLAKE_DATABASE')}}"
      role: AIRBYTE_ROLE
      schema: "{{env_var('DBT_SNOWFLAKE_SCHEMA')}}"
      threads: 1
      type: snowflake
      user: "{{env_var('DBT_SNOWFLAKE_USER')}}"
      password: "{{env_var('DBT_PASSPHRASE')}}"
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
